### ISSUE TITLE
Invalid Date inside datepicker popover

### ISSUE THREAD

**Issue by dvzrd** [miguelalarcos/afwrap-xdatetime#1]
I tried out the package, it was very simple to set up as per your instructions however I ran into a small bug I was hoping you could help me out with.

When I delete the date in the field, it adds invalid date as the field value. This also messes up the datepicker popover and replaces all the dates inside to invalid date. I added a screenshot since it will explain it better than words can:

http://imgur.com/XnF3MFf

Anyway, any ideas how to prevent this? Is there a way to disable the datepicker in a non hacky way, by toggling a method to false or something? 

Thanks for the help and the great package. I love seeing things that aren't dependent on bootstrap coming from the Meteor community.

**Comment by miguelalarcos** [comment]
Hi, thanks for the reporting. I've corrected the code and now, if the date is invalid, it is set automatically to now when focusout. Can you try it? It would be nice to have feedback.

**Comment by dvzrd** [comment]
Hey,

just checked the update, it defaults to now (current date) when I  delete the date value. This solves the issue, thank you!
