### ISSUE TITLE
loading different dates into field - defaults to current date

### ISSUE THREAD

**Issue by dvzrd** [miguelalarcos/afwrap-xdatetime#2]
Hey, 

Sorry to bother you again but I might have found another issue.

I'm having trouble loading different dates into the field. Currently it just adds the now date into the field value no matter what I try.

I have my markup set up like this:

```
{{#with date}}
   {{> afQuickField type='xdatetime' formid='test' name='issued' format='MM/DD/YYYY'}}
   {{> afQuickField type='xdatetime' formid='test' name='expires' format='MM/DD/YYYY'}}
{{/with}}
```

I have a helper in place to add the date in like this:

```
Template['test'].helpers({
  'date': function () {
        var now = moment(),
            later = now.add(1, 'y');
        return {
            issued: now,
            expires: later
        };
    }
});
```

The later variable still returns the current date into the field. I tried hardcoding the later variable into a date string just to test if it wasn't moment's fault just in case but it still doesn't return the variable.

Any thoughts on this?

**Comment by miguelalarcos** [comment]
Don't worry :)

Could you try the next code?

``` javascript
Template['test'].helpers({
  'date': function () {
        var now = moment();
        var later = now.clone().add(1, 'y');
        return {
            issued: now.toDate(),
            expires: later.toDate()
        };
    }
});
```

I am going to investigate other cases. Have you got a git with the example?

**Comment by dvzrd** [comment]
Hey, just tried it but no luck. It still loads current date into the expires field.

I have a git repo of a project using the package but its no specific example. If you want to check it out, it would be here: 

https://github.com/amazingBastard/lockers/blob/master/client/views/lockers/group/locker_group_new.html

https://github.com/amazingBastard/lockers/blob/master/client/views/lockers/group/locker_group_new.js

**Comment by miguelalarcos** [comment]
hum... my example works ok with `.add(1, 'y')`.
This is the code (coffeescript) to set the value:

``` coffee
$.valHooks['xdatetime'] =
  set: (el, value)->
    formid = $(el).attr('formid')
    name = $(el).attr('name')
    path_ = path(formid, name)
    data.remove({path: path_})
    value = moment.utc(value).startOf('minute')   # <------ the important code
    data.insert({path: path_, value:value})
```

Would it be difficult to you to create a small repo with the necessary code to replicate the issue?
You can clone the package and check my example. I continue investigating...

**Comment by dvzrd** [comment]
Ok I'll try to replicate the issue. Most likely I'll paste the link to the repo tomorrow since I need time to set up the example.

Thanks for all the help.

**Comment by dvzrd** [comment]
Hello again,

So I set up some example repos with the issue recreated. The repo is here: https://github.com/amazingBastard/xdatetime-meteor-boilerplate

I added it inside meteor boilerplate just to replicate the environment in case that was what's causing it.
The code would be here: https://github.com/amazingBastard/xdatetime-meteor-boilerplate/tree/master/client/views/home

I also added a very basic meteor app without the boilerplate and minimal dependencies in the same repo. The link to it is here: https://github.com/amazingBastard/xdatetime-meteor-boilerplate/tree/master/xdate-test-vanilla

I'm still not getting the date to change so I don't know what could be causing it.

Sidenote, feel free to re-use the styles for the datepicker: https://github.com/amazingBastard/xdatetime-meteor-boilerplate/blob/master/client/stylesheets/main.less

Thanks again for the help.

**Comment by miguelalarcos** [comment]
Hi, I've looked to the xdate-test-vanilla repo.

You have to use the xdatetime with autoform this way:

``` html
{{#autoForm collection='Test' doc=date class='ui form' id='testForm' type='insert' validation='keyup'}}
```

I'm sorry you can't use `{{#with date}}`

Other thing is that in your model, you have to specify type Date and not String:

``` javascript
Test.attachSchema(new SimpleSchema({
    issued: {
        type: Date,
        label: 'Issue Date',
        optional: true
    },
    expires: {
        type: Date,
        label: 'Expiration Date',
        optional: true
    }
}));
```

Hope that helps.

**Comment by dvzrd** [comment]
That worked! You're awesome, thanks again for the help. 

Let me know if you need any help with this package. I see that the markup of the datepicker could use some restructuring. I can also add css for you if you want.

This is a great package, good job! Thanks!

**Comment by miguelalarcos** [comment]
Thanks to you for contributing to the project!
Help is welcome, so if you think you can improve it then let me know or even make a pull request (this is the first time I ask for a pull request :)

**Comment by dvzrd** [comment]
Cool, I'll send you a pull request sometime this week/weekend. Til' then. Take care.
